queue_rules:
  - name: default
    queue_conditions:
      - status-success=Finish Test
      - label=ready-to-merge
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Finish Test
    merge_method: squash

pull_request_rules:
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(master|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      label:
        remove:
          - ready-to-merge
      delete_head_branch:
  - name: merge PRs labeled ready-to-merge
    conditions: []
    actions:
      queue:
