name: Update Changelog
on: [push,pull_request]

jobs:
  update_changelogs:
    runs-on: ${{ matrix.os }}
    name: Update Changelogs
    timeout-minutes: 30
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-latest] #, windows-latest]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Run Build
        run: npx lerna exec --concurrency 1 --stream -- 'conventional-changelog --preset angular --release-count 2 --commit-path $PWD --pkg $PWD/package.json --verbose --lerna-package $LERNA_PACKAGE_NAME -t $LERNA_PACKAGE_NAME'
