name: Update Changelog
on:
  push:
    tags:
      - '@donmahallem/*@[0-9]+.[0-9]+.[0-9]+'

jobs:
  update_changelogs:
    runs-on: ${{ matrix.os }}
    name: Update Changelogs
    timeout-minutes: 30
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest] #, windows-latest]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: '${{ github.ref }}'
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup Cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps
        run: |
          npm ci
          npx lerna bootstrap --ci
          npm install -g conventional-changelog-cli
      - name: Extract Package Name
        id: package_name
        run: node ./scripts/strip_package_name.js ${{ github.ref }}
      - name: Get color
        run: echo "${{ steps.package_name.outputs.PACKAGE_NAME }} ${{ steps.package_name.outputs.PACKAGE_NAME_SUFFIX }}"
      - name: Run Build Changelog
        run: |
          npx conventional-changelog --preset angular --release-count 2 -u false --commit-path packages/${{ steps.package_name.outputs.PACKAGE_NAME_SUFFIX }} --pkg packages/${{ steps.package_name.outputs.PACKAGE_NAME_SUFFIX }}/package.json -t ${{ steps.package_name.outputs.PACKAGE_NAME }}@ -o TMP_README.md
      - name: Update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: '${{ github.ref }}'
          release_name: 'Release ${{ github.ref }}'
          body_path: ./TMP_README.md
          draft: false
          prerelease: false
