name: Sync branch
on:
  push:
    branches:
    - master

jobs:
  sync-branch:
    name: Update test branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: connor-baer/action-sync-branch@master
        with:
          branch: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false
