name: Update Changelog
on:
  push:

jobs:
  update_changelogs:
    runs-on: ${{ matrix.os }}
    name: Update Changelogs
    timeout-minutes: 30
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest] #, windows-latest]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: '@donmahallem/eslint-config@0.2.5'
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps
        run: |
          npm ci
      - name: Extract Package Name
        id: package_name
        run: |
          echo "::set-output name=PACKAGE_NAME::@donmahallem/rollup-config"
          echo "::set-output name=PACKAGE_NAME_SUFFIX::rollup-config"
      - name: Run Build Changelog
        run: |
          npx conventional-changelog --preset angular --release-count 4 -u false --commit-path ./packages/${{ steps.package_name.outputs.PACKAGE_NAME_SUFFIX }} --pkg ./packages/${{ steps.package_name.outputs.PACKAGE_NAME_SUFFIX }}/package.json -o TMP_README.md --lerna-package ${{ steps.package_name.outputs.PACKAGE_NAME }}
          npx conventional-changelog --preset angular --release-count 4 -u false --commit-path ./packages/${{ steps.package_name.outputs.PACKAGE_NAME_SUFFIX }} --pkg ./packages/${{ steps.package_name.outputs.PACKAGE_NAME_SUFFIX }}/package.json --lerna-package ${{ steps.package_name.outputs.PACKAGE_NAME }}
          npx conventional-changelog --preset angular --release-count 2 -u false --commit-path packages/eslint-config --pkg packages/eslint-config/package.json -t @donmahallem/eslint-config@
      - name: Get color
        run: echo "The selected color is ${{ steps.package_name.outputs.PACKAGE_NAME }}"
      - name: Without fetch tags
        run: |
          git tag --list
      - name: Echo
        run: |
          cat TMP_README.md
          cat package.json
