name: Test
on:
  push:
    - master


jobs:
  build_suite:
    runs-on: ${{ matrix.os }}
    name: Version Release
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        node: [ 16]
        os: [ubuntu-latest] #, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 200
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Deps
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Run Build
        run: npx lerna run build
      - name: Version Packages
        run: npx lerna version --create-release github -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
